text = "hello world"
email = "user123@example.com"
number_str = "123"
tabs = "name\tage\tcity"

print("capitalize():", text.capitalize())
print("casefold():", "HELLO".casefold())
print("center():", text.center(20, "*"))
print("count():", text.count("l"))
print("encode():", text.encode())
print("endswith():", email.endswith(".com"))
print("expandtabs():", tabs.expandtabs(10))
print("find():", text.find("world"))
print("format():", "Name: {}, Age: {}".format("Alice", 25))
print("format_map():", "Name: {name}, Age: {age}".format_map({"name": "Bob", "age": 30}))
print("index():", text.index("world"))
print("isalnum():", "abc123".isalnum())
print("isalpha():", "hello".isalpha())
print("isascii():", "Python3".isascii())
print("isdecimal():", "1234".isdecimal())
print("isdigit():", "123".isdigit())
print("isidentifier():", "my_var".isidentifier())
print("islower():", text.islower())
print("isnumeric():", "123".isnumeric())
print("isprintable():", "Hello\n".isprintable())  # False due to newline
print("isspace():", "   ".isspace())
print("istitle():", "Hello World".istitle())
print("isupper():", "HELLO".isupper())
print("join():", "-".join(["2025", "06", "10"]))
print("ljust():", text.ljust(20, "-"))
print("lower():", "HELLO".lower())
print("lstrip():", "   hello".lstrip())
print("maketrans() & translate():", "hello".translate(str.maketrans("hlo", "HLO")))
print("partition():", email.partition("@"))
print("replace():", text.replace("world", "Python"))
print("rfind():", text.rfind("l"))
print("rindex():", text.rindex("l"))
print("rjust():", text.rjust(20, "-"))
print("rpartition():", email.rpartition("@"))
print("rsplit():", "a,b,c,d".rsplit(",", 2))
print("rstrip():", "hello   ".rstrip())
print("split():", "one two three".split())
print("splitlines():", "Line1\nLine2\nLine3".splitlines())
print("startswith():", text.startswith("hello"))
print("strip():", "   hello   ".strip())
print("swapcase():", "Hello World".swapcase())
print("title():", text.title())
print("upper():", text.upper())
print("zfill():", number_str.zfill(6))
